import { jsPDF } from 'jspdf';
import * as XLSX from 'xlsx';
import { buildExportTables } from '@2wix/export-engine';
import type { ExportFormat, ExportPackageSnapshot } from '@2wix/shared-types';

function saveBlob(content: Blob, fileName: string): void {
  const url = URL.createObjectURL(content);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  a.click();
  URL.revokeObjectURL(url);
}

function csvFromRows(rows: Array<Record<string, string | number>>): string {
  if (rows.length === 0) return '';
  const headers = Object.keys(rows[0] ?? {});
  const escape = (v: string | number) => {
    const s = String(v);
    if (s.includes(',') || s.includes('"') || s.includes('\n')) return `"${s.replaceAll('"', '""')}"`;
    return s;
  };
  const out = [headers.join(',')];
  for (const row of rows) {
    out.push(headers.map((h) => escape(row[h] ?? '')).join(','));
  }
  return out.join('\n');
}

export function downloadExportSnapshot(
  snapshot: ExportPackageSnapshot,
  format: ExportFormat,
  fileName: string
): void {
  const tables = buildExportTables(snapshot);
  if (format === 'csv') {
    const csv = csvFromRows(tables.bomRows);
    saveBlob(new Blob([csv], { type: 'text/csv;charset=utf-8;' }), fileName);
    return;
  }
  if (format === 'xlsx') {
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(tables.summaryRows), 'Summary');
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(tables.bomRows), 'BOM');
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(tables.wallRows), 'Walls');
    XLSX.utils.book_append_sheet(wb, XLSX.utils.json_to_sheet(tables.warningRows), 'Warnings');
    XLSX.writeFile(wb, fileName);
    return;
  }
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  let y = 40;
  const line = (text: string, step = 16) => {
    doc.text(text, 40, y);
    y += step;
  };
  line(`SIP Export Report: ${snapshot.projectSummary.projectTitle}`, 20);
  line(`Project: ${snapshot.projectSummary.projectId}`);
  line(`Version: v${snapshot.projectSummary.versionNumber} (${snapshot.projectSummary.versionId})`);
  line(`Generated at: ${new Date(snapshot.generatedAt).toLocaleString('ru-RU')}`);
  line(`Generated by: ${snapshot.projectSummary.generatedBy ?? '—'}`, 20);
  line('Summary:', 18);
  line(`Floors: ${snapshot.projectSummary.floorsCount}`);
  line(`Included walls: ${snapshot.specSummary.wallCountIncluded}`);
  line(`Panels: ${snapshot.specSummary.totalPanels}`);
  line(`Trimmed panels: ${snapshot.specSummary.totalTrimmedPanels}`);
  line(`Area m2: ${snapshot.specSummary.totalPanelAreaM2}`);
  line(`Warnings: ${snapshot.warnings.length}`, 20);
  line('Aggregated BOM:', 18);
  for (const row of tables.bomRows.slice(0, 20)) {
    line(`${row.code} | ${row.name} | ${row.unit} ${row.qty}`, 14);
  }
  if (tables.warningRows.length > 0) {
    line('Warnings:', 18);
    for (const w of tables.warningRows.slice(0, 15)) {
      line(`${w.severity} [${w.code}] ${w.message}`, 14);
    }
  }
  doc.save(fileName);
}
