const AVAILABLE_PLACEHOLDERS = [
  { value: '{clientNumber}', label: 'Номер клиента' },
  { value: '{firstName}', label: 'Имя' },
  { value: '{lastName}', label: 'Фамилия' },
  { value: '{middleName}', label: 'Отчество' },
  { value: '{iin}', label: 'ИИН' },
  { value: '{phone}', label: 'Телефон' },
  { value: '{email}', label: 'Email' },
  { value: '{constructionAddress}', label: 'Адрес строительства' },
  { value: '{livingAddress}', label: 'Адрес проживания' },
  { value: '{objectName}', label: 'Название объекта' },
  { value: '{constructionDays}', label: 'Срок строительства (дни)' },
  { value: '{totalAmount}', label: 'Общая сумма' },
  { value: '{totalAmountWords}', label: 'Общая сумма прописью' },
  { value: '{deposit}', label: 'Сумма депозита' },
  { value: '{depositWords}', label: 'Сумма депозита прописью' },
  { value: '{firstPayment}', label: 'Первая оплата' },
  { value: '{firstPaymentWords}', label: 'Первая оплата прописью' },
  { value: '{secondPayment}', label: 'Вторая оплата' },
  { value: '{secondPaymentWords}', label: 'Вторая оплата прописью' },
  { value: '{thirdPayment}', label: 'Третья оплата' },
  { value: '{thirdPaymentWords}', label: 'Третья оплата прописью' },
  { value: '{fourthPayment}', label: 'Четвертая оплата' },
  { value: '{fourthPaymentWords}', label: 'Четвертая оплата прописью' },
  { value: '{additionalWorks}', label: 'Дополнительные работы' },
  { value: '{estimateTable}', label: 'Таблица сметы' }
]; 